name: slimsocial_for_facebook
description: Webview to securely navigate Facebook
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 10.0.12+112

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_jailbreak_detection: ^1.10.0
  flutter_webview_pro: 3.0.1+4
  flutter_custom_tabs: 1.0.4
  url_launcher: 6.1.10
  permission_handler: 10.2.0
  shared_preferences: 2.1.0
  flutter_launcher_icons: 0.13.1
  app_links: 3.4.2
  settings_ui: 2.0.2
  flutter_riverpod: 2.3.6
  in_app_purchase: 3.1.5
  fluttertoast: 8.2.1
  easy_localization: ^3.0.1
  package_info_plus: 3.1.2
  restart_app: 1.1.2
  google_fonts: 4.0.4
  in_app_review: 2.0.9
  share_plus: 6.3.4
  flutter_file_downloader: 1.1.2
  open_file_plus: 3.4.1
  native_flutter_proxy: 0.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  #android: "launcher_icon"
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lang/
